### ISSUE TITLE
Use simple php app

### ISSUE THREAD

**Issue by roshanjonah** [sherifabdlnaby/kubephp#13]
Sorry I feel like I am the only one asking silly questions here but what if you are hosting "Yii" app which doesn't serve from the `public` folder. Or if you have just `index.php` which you want to use without any composer. How would I go about then for both these scenarios? What parts would I need to modify in `Dockerfile` or maybe I don't need to touch that file at all?

**Comment by sherifabdlnaby** [comment]
The Image is a PHP-FPM + Nginx setup that is pre-configured for typical modern PHP Frameworks like Laravel & Symfony, I don't have much experience for Yii.

That said, you can refactor the image to run pure vanilla PHP, I'd recommend starting with the nginx and php-fpm configuration to match the Yii framework directory structure, then you can clean out the Composer references.
