### ISSUE TITLE
Stuck on "► Running Composer Install..."

### ISSUE THREAD

**Issue by Danielss89** [sherifabdlnaby/kubephp#30]
Hello
I'm trying this out for my application, but when i run docker-compose up -d, the app container is stuck at:
► Running Composer Install...
No more log output after that.
I tried deleting the vendor folder, but same result.

**Comment by Danielss89** [comment]
Ok i had to wait a bit longer it seems. I now got som out, but it failed because of timeout.
[Symfony\Component\Process\Exception\ProcessTimedOutException]
The process "'/usr/local/bin/php' '--php-ini=/usr/local/etc/php/php.ini' './bin/console' cache:clear" exceeded the timeout of 300 seconds.

What could be the reason for the image being so slow? I just changed from another image, in which composer install worked fine and fast.

**Comment by Danielss89** [comment]
<img width="1260" alt="Screenshot 2022-09-15 at 22 05 20" src="https://user-images.githubusercontent.com/632956/190498487-38b0e046-2f25-4d03-b626-80e2402693f9.png">
Something happened now, but talking ~12 minutes, that seems overkill :O

**Comment by sherifabdlnaby** [comment]
@Danielss89 That's obviously not normal 😅  It should almost start instantaneously, one common gotcha is having XDebug Intercept `composer` commands, check your IDE Configuration to ignore this kind of XDebug Sessions, or stop listening for XDebug Sessions altogether.

**Comment by Danielss89** [comment]
That was it! I had another project open which caught it :O
Thank you!
